### ISSUE TITLE
177. Nth Highest Salary - error in New UI

### ISSUE THREAD

**Issue by bannovdaniil** [LeetCode-Feedback/LeetCode-Feedback#10438]
#### Your LeetCode username
bannovdaniil

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
code don't work in new UI

#### Code you used for Submit/Run operation

```
CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT

BEGIN
DECLARE POS INT;
SET POS=N-1;

  RETURN (
      # Write your MySQL query statement below.
      SELECT DISTINCT Salary
       FROM Employee
       ORDER BY Salary
      DESC LIMIT POS, 1
  );
END
```

#### Language used for code
MySQL

#### Screenshots
in new UI
![image](https://user-images.githubusercontent.com/96119195/208596723-ff96ef00-41af-4e24-8dee-51435f59f21c.png)

in old UI
![177-in-old](https://user-images.githubusercontent.com/96119195/208596769-88dbc399-70f1-4774-ab06-257f0e3b41f9.PNG)

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem and it works fine on the new vision.
We appreciate your support!
![Screen Shot 2022-12-20 at 1 30 57 PM](https://user-images.githubusercontent.com/103138242/208740201-53127c3d-e57d-49e6-9c46-fc096f78d927.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
https://project.feishu.cn/leetcode/us_tickets/detail/3357391?parentUrl=%2Fleetcode%2FworkObjectView%2Fus_tickets%2FvHtNOOSVR

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem. The issue should be fixed, we appreciate your report! Please let us know if you have any questions.
![Screen Shot 2023-01-13 at 5 41 56 PM](https://user-images.githubusercontent.com/103138242/212432768-1e5d4247-f636-447c-892c-d46c55ae1216.png)

**Comment by ujjwalgarg** [comment]
The issue persists. I have been getting runtime errors without any prompt for any query I run.
<img width="1440" alt="Screenshot 2023-01-20 at 9 57 05 AM" src="https://user-images.githubusercontent.com/16412534/213729350-9f5a0ab7-3639-4963-8d2e-829772bc5c69.png">

**Comment by AgentIvan** [comment]
> The issue persists. I have been getting runtime errors without any prompt for any query I run. <img alt="Screenshot 2023-01-20 at 9 57 05 AM" width="1440" src="https://user-images.githubusercontent.com/16412534/213729350-9f5a0ab7-3639-4963-8d2e-829772bc5c69.png">

you are using wrong syntax
try:
```
SELECT DISTINCT(salary)
      FROM Employee
      ORDER BY salary DESC
      LIMIT N, 1
      ```
