### ISSUE TITLE
Editor not showing expected Python3 code for Two Sum

### ISSUE THREAD

**Issue by tannerdolby** [LeetCode-Feedback/LeetCode-Feedback#14296]
#### Your LeetCode username
gnawlix

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The [Two Sum](https://leetcode.com/problems/two-sum/) problem has the wrong programming language in editor for Python3. It shows Java code instead of Python.

#### Expected behavior

To see Python3 code in the editor.

#### Screenshots
<img width="1280" alt="Screen Shot 2023-06-22 at 11 34 38 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/48612525/755f27ef-d521-4e32-867f-a7cbd36e2202">

**Comment by pushkarkumarlal** [comment]
The Issue Has been resolved.
This is not an bug
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/72812113/976e1e17-3cf8-4d4b-ae57-f550d06bf59c)

**Comment by tannerdolby** [comment]
@pushkarkumarlal unfortunately it doesn't seem to be resolved on Chrome Version 114.0.5735.133 (Official Build) (x86_64). I reset browser cache, tried in incognito window, still the issue persists on the most up-to-date Chome. I will wait for a Leetcode team member to diagnosis or look into the issue since its still persisting. Thanks!

Here is a screen recording for your reference:


https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/48612525/83915af2-b524-4149-8027-7b15c8b08b3d
