### ISSUE TITLE
[BUG] - Time limit too low for Python - 3599. Partition Array to Minimize XOR

### ISSUE THREAD

**Issue by hexawhale** [LeetCode-Feedback/LeetCode-Feedback#30243]
### LeetCode Username

killer-whale

### Problem Number, Title, and Link

3599. Partition Array to Minimize XOR https://leetcode.com/problems/partition-array-to-minimize-xor/description/

### Bug Category

Problem constraints

### Bug Description

It is possible to submit an O(N^2 * K) solution in Python and receive `Time Limit Exceeded`, even though the solution should be `Accepted` given the constraints, where N and K can be at most `250`. The time limit is too strict.

### Language Used for Code

Python/Python3

### Code used for Submit/Run operation

```bash
class Solution:
    def minXor(self, nums: List[int], k: int) -> int:
        n = len(nums)
        @cache
        def best(i, k):
            if i == n:
                return 0 if k == 0 else inf
            if k == 0:
                return inf
            res = inf
            xor = 0
            for j in range(i, n):
                xor ^= nums[j]
                res = min(res, max(xor, best(j + 1, k - 1)))
            return res
        r = best(0, k)
        best.cache_clear()
        return r
```

### Expected behavior

The above solution should be `Accepted` and the Weekly Contest 456 should be rejudged to correct the rankings for those who solved this problem with an acceptable time complexity.

**Comment by wktang** [comment]
oj-leetcode commented: Hello,

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by wktang** [comment]
Epiphania_Ekenimoh commented: Hello there,

The issue you reported has been resolved. Please feel free to verify and retry.

We apologize for any inconvenience this may have caused and appreciate your patience while we worked to resolve the issue. If you have any further questions or concerns, please do not hesitate to contact us.

Thank you,
LeetCode Support Team

**Comment by hexawhale** [comment]
There is an issue. Weekly Contest 456 still shows the following contest submission as `Time Limit Exceeded`, even though it should be `Accepted`: https://leetcode.com/contest/weekly-contest-456/submissions/detail/1679870681/
Here is another example of a contest submission that still incorrectly shows `Time Limit Exceeded`: https://leetcode.com/contest/weekly-contest-456/submissions/detail/1679842042/
These submissions were made during the contest. The contest needs to be rejudged so that these submissions get `Accepted`.

**Comment by wktang** [comment]
Epiphania_Ekenimoh commented: Hello there,

Thanks for bringing this to our attention!

The issue has been resolved. Please feel free to verify and retry.

We apologize for any inconvenience this may have caused and appreciate your patience while we worked to resolve the issue. If you have any further questions or concerns, please do not hesitate to contact us.

Thank you,
LeetCode Support Team

**Comment by hexawhale** [comment]
The issue is not resolved. I made this submission 36 minutes into Weekly Contest 456 and the status of the submission has not been changed to Accepted: https://leetcode.com/contest/weekly-contest-456/submissions/detail/1679870681/

The status of this submission results in an erroneous 5 minute penalty which is still present on the contest leaderboard. My leetcode username is killer-whale and my rank is currently 111 with a finish time of 55:21 in this contest, but I should be around rank 85 with a finish time of 50:21. The 5 minute penalty from this contest submission has not been removed.

To verify that the issue is resolved, the submission that I linked should have its status changed to Accepted and my contest finish time should be rejudged as 50:21, not 55:21.

**Comment by hexawhale** [comment]
The issue has now been resolved.
