### ISSUE TITLE
[BUG] - datastructure-js - environment uses modern code, but Editor uses ancient types

### ISSUE THREAD

**Issue by Alexsey** [LeetCode-Feedback/LeetCode-Feedback#32159]
### LeetCode Username

Aleksey

### Problem Number, Title, and Link

https://leetcode.com/problems/number-of-orders-in-the-backlog

### Bug Category

Editorial

### Bug Description

[datastructure-js](https://datastructures-js.info/docs) is a library that is according to the [official LeetCode docs](https://support.leetcode.com/hc/en-us/articles/360011833974-What-are-the-environments-for-the-programming-languages), is available in JavaScript and TypeScript runtimes

The problem is that the Editor is showing type errors based on a very old version of library types, but the runtime is using a relevant version of the library

Here are examples based on `MaxPriorityQueue` and `MinPriorityQueue`. If we type the code that is valid according the actual library docs, the editor will give us type errors:

1. Here it complains about `'PriorityQueueOptions'`. But `'PriorityQueueOptions'` [was removed in March 2022](https://github.com/datastructures-js/priority-queue/commit/d6958a7b4da4312556d9e816dcea6437ad65a8e0)
<img width="1286" height="219" alt="Image" src="https://github.com/user-attachments/assets/bc713d2c-14fe-4e29-bb6d-c672ad260a9c" />

2. Here it complains about missing `'[Symbol.iterator]()`. But `'[Symbol.iterator]()'` [was added in June 2023](https://github.com/datastructures-js/priority-queue/commit/841297046a144b167c0c984f8c7f3c3489850bc2)
<img width="1197" height="265" alt="Image" src="https://github.com/user-attachments/assets/0ba0d519-6806-407f-be96-db13d9c610ce" />

<details>
  <summary>The code that suppresses type error, but works in runtime:</summary>

```typescript
function getNumberOfBacklogOrders(orders: [price: number, amount: number, orderType: 0 | 1][]): number {
  // @ts-ignore
  const buys = new MaxPriorityQueue(([price, _amount]: [price: number, amount: number]) => price)
  // @ts-ignore
  const sells = new MinPriorityQueue(([price, _amount]: [price: number, amount: number]) => price)
  for (let [price, amount, type] of orders) {
    if (type == 0) {
      while (amount && sells.size() && sells.front()[0] <= price) {
        if (sells.front()[1] > amount) {
          sells.front()[1] -= amount
          amount = 0
        } else {
          amount -= sells.front()[1]
          sells.dequeue()
        }
      }

      if (amount) {
        buys.enqueue([price, amount])
      }
    } else {
      while (amount && buys.size() && buys.front()[0] >= price) {
        if (buys.front()[1] > amount) {
          buys.front()[1] -= amount
          amount = 0
        } else {
          amount -= buys.front()[1]
          buys.dequeue()
        }
      }

      if (amount) {
        sells.enqueue([price, amount])
      }
    }
  }

  let open = 0

  // @ts-ignore
  for (const [_price, amount] of buys) {
    open = (open + amount) % 1_000_000_007
  }

  // @ts-ignore
  for (const [_price, amount] of sells) {
    open = (open + amount) % 1_000_000_007
  }

  return open
}
```
</details>

<details>
  <summary>The code that satisfies types, but crashes at runtime</summary>

```typescript
function getNumberOfBacklogOrders(orders: [price: number, amount: number, orderType: 0 | 1][]): number {
  const buys = new MaxPriorityQueue({priority: ([price, _amount]: [price: number, amount: number]) => price})
  const sells = new MinPriorityQueue({priority: ([price, _amount]: [price: number, amount: number]) => price})

  return 1
}
```

No error while in the Editor:

<img width="1105" height="127" alt="Image" src="https://github.com/user-attachments/assets/dddc8bfc-3111-4117-8500-ee0e55f669fe" />

But crashes on submit.
**Note proper type errors from the runtime - error message references modern types, not ancient**:

<img width="1287" height="564" alt="Image" src="https://github.com/user-attachments/assets/b2efdc7e-8f0f-4bc3-96d5-133d6aeb40e6" />

</details>

### Language Used for Code

TypeScript

### Code used for Submit/Run operation

```bash

```

### Expected behavior

The version of the types in the Editor must match the version of the `datastructure-js` library in the runtime

**Comment by oj-leetcode** [comment]
oj-leetcode commented: Hello,

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by oj-leetcode** [comment]
Epiphania_Ekenimoh commented: Hello there,

The issue you reported has been resolved. Please feel free to verify and retry. If the problem continues to persist, please let us know so we can update our engineering team.

We apologize for any inconvenience this may have caused and appreciate your patience while we worked to resolve the issue. If you have any further questions or concerns, please do not hesitate to contact us.

Thank you,
LeetCode Support Team

**Comment by Alexsey** [comment]
I've tried the code from the initial post after a hard refresh (Ctrl+F5) of the page, but the bug persists:

1. Type error 1:<img width="1296" height="232" alt="Image" src="https://github.com/user-attachments/assets/3e2e2191-fa0c-4b2a-9fbc-8fd9ff406aaa" />

2. Type error 2:<img width="1170" height="237" alt="Image" src="https://github.com/user-attachments/assets/b26ea056-b8c8-4648-af88-dfe587a33ba2" />

3. No type error, although this crashes at runtime:<img width="1129" height="249" alt="Image" src="https://github.com/user-attachments/assets/46b85dab-3e3f-4f25-a16f-46e612ccec2e" />

**Comment by oj-leetcode** [comment]
Epiphania_Ekenimoh commented: Hello there,

Thanks for following up!

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
