### ISSUE TITLE
Something is wrong with JS interpretation - 117. Populating Next Right Pointers in Each Node II

### ISSUE THREAD

**Issue by nineonine** [LeetCode-Feedback/LeetCode-Feedback#8362]
#### Your LeetCode username
dnox

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
for some reason interpretation of return type results in type check error. Try to run with the following test case:
```
[1]
```

According to the problem AC that should succeed.

However, I am getting:

```
Line 117 in solution.js
             throw new TypeError(__serialize__(ret) + " is not valid value for the expected return type Node");
             ^
TypeError: {"val":1,"left":null,"right":null,"next":null} is not valid value for the expected return type Node
    Line 117: Char 20 in solution.js (Object.<anonymous>)
    Line 16: Char 8 in runner.js (Object.runner)
    Line 49: Char 26 in solution.js (Object.<anonymous>)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

#### Code you used for Submit/Run operation

```
var connect = function(root) {
    
    return root
}
```

#### Language used for code
JavaScript

#### Expected behavior
no type mismatch error

**Comment by nineonine** [comment]
I tried 3 top js solutions with highest ratings and they all fail same way

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!
This issue already noticed by our content team and our developer working on it.

**Comment by rollschild** [comment]
can confirm the issue. I just do `return root;` and it still gives me runtime error.

**Comment by Adtsw** [comment]
The error still remains with JS. BFS seems to be the perfect approach, but unfortunately, leetcode fails to recognize it.

**Comment by sjuchno** [comment]
If you want to submit your code you can switch to TypeScript, and paste in your javascript code. No issues there.

**Comment by SergiiMost** [comment]
> Thank you for reaching out to us! This issue already noticed by our content team and our developer working on it.

Any updates? Still broken.

**Comment by hhmmak** [comment]
The issue still persists when using JS. Please update

**Comment by Adtsw** [comment]
The issue still persists when working with JS.

**Comment by alessiopece** [comment]
Bumping this up. Still an issue.

**Comment by roman-zhishkevich** [comment]
Still an issue.

**Comment by JowieXiang** [comment]
The issue still persists. 
As a workaround, we could use Typescript instead with the exact same JS code, and the validation works.
![image](https://user-images.githubusercontent.com/31316150/212536050-d98265a3-3ff4-4119-b6e5-b3056f0a72f1.png)

**Comment by LC-Pam** [comment]
Thank you for your time. 

Sorry for the late reply.

The issue should be fixed. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by Abhinav-676** [comment]
![Screenshot 2024-05-22 144816](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71707090/89a975cd-1760-4ab2-83e4-47fe1786fab0)


The issue still persists, I also returned the root.

**Comment by pricetula** [comment]
still persists
